export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as BannerSlider } from './homePageComponents/BannerSlider'
export { default as About } from './homePageComponents/About'
export { default as Blogs } from './homePageComponents/Blogs'
export { default as Features } from './homePageComponents/Features'
